### ISSUE TITLE
Unable to install Xcode in macOS 10.14.5

### ISSUE THREAD

**Issue by americanhanko** [microsoft/macos-cookbook#199]
## Describe the Bug 
When using a macOS Vagrant base box running 10.14.5, and attempting to install Xcode 10.2 and Xcode 10.2.1 using the newest version of macOS cookbook (3.0.1), the Xcode installation hangs, does not complete the installation, and eventually times out. 

## Error Message  

> **Could not find a writable folder for the contents of "Xcode_10.2.xip". Try moving it to a writable folder**

![Screen Shot 2019-05-14 at 7 03 03 PM](https://user-images.githubusercontent.com/8458267/57934900-7458e380-7875-11e9-8c79-3c89d690c626.png)

**Comment by v-anshie** [comment]
Not sure if this is related but [10.14.5 release](https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_5_release_notes) has a new security feature that "Kernel extensions signed after April 7, 2019 must be notarized in order to load on macOS 10.14.5. (50016570)" 

"The system fails to register tickets stapled to installer packages not scanned by Gatekeeper, which causes newly installed kernel extensions to fail to load if Internet access isn’t available. This can occur if a user launches installation from a local folder or an enterprise uses automated tools to deploy an installer. This issue doesn’t affect stapled disk images, apps, or kext bundles. (50205533)"

**Comment by jazaval** [comment]
This is resolved with the closure [https://github.com/xcpretty/xcode-install/issues/339](https://github.com/xcpretty/xcode-install/issues/339).
