### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brax4444** [microsoft/macos-cookbook#227]
## Describe the Bug 
I'm trying to install Xcode 11.6 on a fresh system with this cookbook. /opt/chef-workstation/embedded/bin/xcversion does not exist because this cookbook has not run before. Please advise? 

## Error Message  
Errno::ENOENT No such file or directory - /opt/chef-workstation/embedded/bin/xcversion

**Comment by jazaval** [comment]
Hey @brax4444 - the default `xcode` action array should install the xcversion gem for you. If you're explicitly declaring an `action` for in your resource call, make sure to put `:install_gem` first in the array.

**Comment by brax4444** [comment]
Thanks for the very quick reply @jazaval. To keep this as simple as possible, I wanted to get a clean run first with `xcode '11.6'` on macOS 10.15.5. I am using an Apple ID creds databag for auth. If the system has rbenv, is that likely affecting where the gem is installed? I notice in the code it appears to expect it to be in the Chef dir's bin directory.

**Comment by jazaval** [comment]
The resource does explicitly install xcversion into `/opt/chef/embedded/bin/`, so if you're running chef-client from your full Chef Workstation / ChefDK install you may run into issues. 

Try installing the client outside of a development environment via `curl -L https://omnitruck.chef.io/install.sh | sudo bash`, since that should run out of `/opt/chef`. Alternatively, test out your recipe via Test Kitchen, which mimics a client install by default.

**Comment by brax4444** [comment]
I do believe you're right that this is caused by two chef-clients on the same system. Thank you.
