### ISSUE TITLE
2MFA bypass

### ISSUE THREAD

**Issue by smuel09** [microsoft/macos-cookbook#232]
## Describe the feature  
Clear Block when account has 2MFA enabled (no option to disable anymore)

## Describe the reasoning behind the feature  
Simple xcode install fails

**Comment by jazaval** [comment]
Hi @smuel09, 

In order to use an Apple ID with the `xcode` resource, it must not have 2FA enabled. Apple has stopped allowing creation of new Apple IDs without 2FA, so you must supply an Apple ID that was created before this change, or disable 2FA if the account allows it. The other option is to host your own copy of the Xcode xip and provide the URI to the `download_url` property of the `xcode` resource.

**Comment by smuel09** [comment]
Thank you for replying,
That is what I was afraid of...
Do you have any suggestions apart from hosting the xcode installation them selfs?

**Comment by jazaval** [comment]
Unfortunately your only other option would be to use an old Apple ID that hasn’t been upgraded to 2FA. Some Apple IDs may still give you the option to  disable it as well - try viewing the security section at appleid.apple.com.
