### ISSUE TITLE
'latest' tag for versions of Xcode

### ISSUE THREAD

**Issue by ehanlon** [microsoft/macos-cookbook#93]
Certain wotkflows work off of the 'latest' stable version of Xcode. It would be nice to be able to specify 'latest' for the version property.

**Comment by jazaval** [comment]
the `command_line_tools` resource supports this, but `xcode` still does not.

**Comment by jazaval** [comment]
Given how complex determining the "latest" Xcode actually turned out to be this WWDC season, I think I'm putting this feature outside the scope of this resource. There were instances where we had betas of `11.0` available that were "newer" (i.e., released most recently) than betas of `11.1`, despite 11.1 being "later" version-wise. I'd rather those decisions be declared explicitly.

There is an exact copy of this feature request on the `xcode-install` gem (https://github.com/xcpretty/xcode-install/issues/344), which would likely deal with the same complexity, but I'll defer to them to implement it or not.
